services:
  rica_s_id_cuclark:
    container_name: rica_s_id_cuclark
    entrypoint:
      - /bin/bash
    hostname: rica_s_id_cuclark
    image: alkanlab/cuclark:latest
    ipc: private
    logging:
      driver: json-file
      options: {}
    networks:
      - rica_s_net
    stdin_open: true
    tty: true
    volumes:
      - /home/ricardo/projects/rica_s:/rica_s
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

networks:
  rica_s_net:
    external: true
